//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD5Crtpre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class1
    {
        public int Id { get; set; }
        public string KullaniciName { get; set; }
        public string Sifre { get; set; }
        public string Salt { get; set; }
    }
}
